apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
  namespace: mywebapp-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywebapp
  template:
    metadata:
      labels:
        app: mywebapp
    spec:
      containers:
        - name: mywebapp
          image: 957478052660.dkr.ecr.us-east-1.amazonaws.com/mywebapp:latest
          ports:
            - containerPort: 8080
