pipeline {
    agent any

    environment {
        AWS_REGION     = 'us-east-1'
        ECR_REPO       = '957478052660.dkr.ecr.us-east-1.amazonaws.com/mywebapp'
        IMAGE_TAG      = 'latest'
        KUBE_NAMESPACE = 'mywebapp-ns'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build WAR') {
            steps {
                dir('mywebapp') {
                    bat 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('mywebapp') {
                    bat """
                        docker build -t %ECR_REPO%:%IMAGE_TAG% .
                    """
                }
            }
        }

        stage('Login & Push to ECR') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'aws_cred',
                    usernameVariable: 'AWS_ACCESS_KEY_ID',
                    passwordVariable: 'AWS_SECRET_ACCESS_KEY'
                )]) {
                    bat """
                        aws configure set aws_access_key_id %AWS_ACCESS_KEY_ID%
                        aws configure set aws_secret_access_key %AWS_SECRET_ACCESS_KEY%
                        aws configure set default.region %AWS_REGION%
                        aws ecr get-login-password --region %AWS_REGION% | docker login --username AWS --password-stdin %ECR_REPO%
                        docker push %ECR_REPO%:%IMAGE_TAG%
                    """
                }
            }
        }

        stage('Deploy to EKS') {
            steps {
                bat """
                    aws eks update-kubeconfig --region %AWS_REGION% --name my-eks-cluster
                    kubectl apply -f mywebapp\\k8s-manifests\\namespace.yaml || exit /b 0
                    kubectl apply -f mywebapp\\k8s-manifests\\deployment.yaml -n %KUBE_NAMESPACE%
                    kubectl apply -f mywebapp\\k8s-manifests\\service.yaml -n %KUBE_NAMESPACE%
                    kubectl rollout status deployment/mywebapp -n %KUBE_NAMESPACE%
                """
            }
        }
    }

    post {
        success {
            echo '✅ Deployment completed successfully on EKS!'
        }
        failure {
            echo '❌ Pipeline failed. Please check logs in Jenkins console.'
        }
    }
}
