pipeline {
    agent any

    environment {
        AWS_REGION     = 'us-east-1'
        ECR_REPO       = '957478052660.dkr.ecr.us-east-1.amazonaws.com/mywebapp'
        IMAGE_TAG      = "latest"
        KUBE_NAMESPACE = 'mywebapp-ns'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build WAR') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                  docker build -t $ECR_REPO:$IMAGE_TAG .
                '''
            }
        }

        stage('Login & Push to ECR') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws_credentials'
                ]]) {
                    sh '''
                      aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO
                      docker push $ECR_REPO:$IMAGE_TAG
                    '''
                }
            }
        }

        stage('Deploy to EKS') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws_credentials'
                ]]) {
                    sh '''
                      aws eks update-kubeconfig --region $AWS_REGION --name my-eks-cluster
                      kubectl apply -f k8s-manifests/namespace.yaml || true
                      kubectl apply -f k8s-manifests/deployment.yaml -n $KUBE_NAMESPACE
                      kubectl apply -f k8s-manifests/service.yaml -n $KUBE_NAMESPACE
                      kubectl rollout status deployment/mywebapp -n $KUBE_NAMESPACE
                    '''
                }
            }
        }
    }
}
